---
name: Update Audio
on:
  workflow_dispatch: null
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Generating audio.json
        run: |
          python ./py/generate_audio.py
      - name: Create Commit
        run: |
          git add .
          git config --global user.email "bot@github.com"
          git config --global user.name "Github Bot"
          git commit -m "[Update] $(cat ./data/version.txt)"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: update
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "[Update] Audio $(cat ./data/version.txt)" --body "$(cat ./data/version.txt)" --head update
